### ISSUE TITLE
Sonic GLVL Wii U should have a batch convert option.

### ISSUE THREAD

**Issue by SonicTheSpeedhog230** [DarioSamo/libgens-sonicglvl#30]
So I have been ripping Mario and Sonic 2016 with the libgens-sonicglvl-WiiU and I get 400 .model files from the pac.00 files. I just wish that the Sonic GLVL and all its edited or cloned version will have a batch convert modelfbx something like modelfbxbatchconvert.exe 

That way it wouldn't have to be so tedious wanting to convert 400+ .model files at a time. If anyone else agrees with me please feel free to reply!.

I got the Wii U one from here -- https://github.com/ActualMandM/libgens-sonicglvl/tree/WiiU

**Comment by ActualMandM** [comment]
Why are you creating an issue for a repository that this branch isn't on, especially if its an unofficial build?

**Comment by DarioSamo** [comment]
As for the actual question.

I disagree that command line tools specifically for batching should be made. Mostly because it's useless to maintain. Just write the batch script in whatever language you prefer and call the command line tool through it.

There's an example of this in bin/modelfbx-convert-example.bat
```
for %%f in (Sonic/*.anm.hkx) do modelfbx Sonic/chr_Sonic_HD.model Sonic/chr_Sonic_HD.skl.hkx Sonic/%%f Sonic/%%f.fbx
```

**Comment by ActualMandM** [comment]
> To be fair, they can't really add the issue in a fork unless you enable it on the repo's settings.

Ah, I forgot GitHub disables it by default.
